import HeroAnimations from "@/components/hero-animations";
const tracks=[['01','AI / ML','Build systems that learn, adapt and create.'],['02','Web','Ship fast, expressive products for the real world.'],['03','Cyber','Find weak points. Design stronger systems.'],['04','Open Innovation','No box. No brief. Just a problem worth solving.']];
export default function Home(){return <main className="noise overflow-hidden bg-[#07070a]">
<section className="relative min-h-screen grid-bg"><HeroAnimations/><nav className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><div className="text-sm font-black tracking-[-.04em]">HACKNOVATE<span className="text-white/40">26</span></div><a href="#about" className="rounded-full border border-white/15 px-4 py-2 text-xs font-bold uppercase tracking-wider transition hover:bg-white hover:text-black">Explore</a></nav><div className="relative z-10 mx-auto flex min-h-[calc(100vh-88px)] max-w-6xl flex-col justify-center px-6 pb-24 pt-10"><p className="hero-kicker mb-6 text-xs font-bold uppercase tracking-[.3em] text-white/50">24 hours · one idea · infinite possibilities</p><h1 className="hero-title max-w-5xl text-[clamp(4rem,12vw,10rem)] font-black leading-[.82] tracking-[-.08em]">BUILD.<br/><span className="text-white/35">BREAK.</span><br/>INNOVATE.</h1><p className="hero-copy mt-8 max-w-xl text-base leading-7 text-white/55">A high-energy hackathon for builders who would rather prototype the future than wait for it.</p><div className="hero-actions mt-8 flex flex-wrap gap-3"><a href="#tracks" className="rounded-full bg-white px-6 py-3 text-sm font-bold text-black transition hover:scale-105">View tracks ↗</a><a href="#about" className="rounded-full border border-white/15 px-6 py-3 text-sm font-bold transition hover:border-white/40">Why Hacknovate?</a></div></div><div className="absolute bottom-0 left-0 right-0 h-px bg-white/10"/></section>
<section id="about" className="mx-auto max-w-6xl px-6 py-28"><div className="reveal grid gap-12 md:grid-cols-[.8fr_1.2fr]"><p className="text-xs font-bold uppercase tracking-[.25em] text-white/35">/ 01 — THE IDEA</p><div><h2 className="max-w-3xl text-4xl font-black leading-tight tracking-[-.04em] md:text-6xl">Don&apos;t just attend a hackathon. <span className="text-white/35">Leave something behind.</span></h2><p className="mt-7 max-w-2xl text-lg leading-8 text-white/50">Hacknovate is a place to turn rough ideas into working prototypes, meet people who obsess over building, and learn by shipping.</p></div></div></section>
<section id="tracks" className="border-y border-white/10 bg-white/[.02] py-28"><div className="mx-auto max-w-6xl px-6"><div className="reveal mb-14 flex items-end justify-between gap-6"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.25em] text-white/35">/ 02 — TRACKS</p><h2 className="text-4xl font-black tracking-[-.04em] md:text-6xl">Pick a problem.</h2></div><span className="hidden text-sm text-white/35 md:block">01 — 04</span></div><div className="divide-y divide-white/10 border-y border-white/10">{tracks.map(([num,name,desc])=><div key={num} className="group grid gap-4 py-8 md:grid-cols-[80px_1fr_1.2fr] md:items-center"><span className="text-sm text-white/25">{num}</span><h3 className="text-2xl font-bold transition group-hover:translate-x-2 md:text-4xl">{name}</h3><p className="text-white/40 md:text-right">{desc}</p></div>)}</div></div></section>
<section className="mx-auto max-w-6xl px-6 py-28"><div className="reveal grid gap-12 md:grid-cols-[1fr_.8fr]"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.25em] text-white/35">/ 03 — THE BUILD</p><h2 className="text-5xl font-black leading-none tracking-[-.06em] md:text-8xl">IDEA<br/><span className="text-white/25">→</span> PROTOTYPE<br/><span className="text-white/25">→</span> IMPACT</h2></div><div className="flex flex-col justify-end"><p className="text-lg leading-8 text-white/45">Work with a team. Make trade-offs. Break your first version. Ship a better one.</p><div className="progress-wrap mt-10 h-px bg-white/10"><div className="progress-line h-px w-0 bg-white"/></div><div className="mt-4 flex justify-between text-xs text-white/30"><span>START</span><span>SHIP</span></div></div></div></section>
<section className="overflow-hidden border-y border-white/10 py-5"><div className="marquee flex w-max gap-8 whitespace-nowrap text-5xl font-black uppercase tracking-[-.05em] text-white/[.08]"><span>BUILD THE UNEXPECTED ✦ BUILD THE UNEXPECTED ✦ BUILD THE UNEXPECTED ✦ BUILD THE UNEXPECTED ✦</span><span>BUILD THE UNEXPECTED ✦ BUILD THE UNEXPECTED ✦ BUILD THE UNEXPECTED ✦ BUILD THE UNEXPECTED ✦</span></div></section>
<footer className="mx-auto max-w-6xl px-6 py-20"><div className="reveal rounded-3xl border border-white/10 bg-white/[.03] p-8 md:p-14 glow"><p className="text-xs font-bold uppercase tracking-[.25em] text-white/35">/ READY?</p><h2 className="mt-5 max-w-3xl text-5xl font-black tracking-[-.06em] md:text-8xl">MAKE<br/>SOMETHING<br/><span className="text-white/30">MATTER.</span></h2><a href="#" className="mt-10 inline-flex rounded-full bg-white px-7 py-3 text-sm font-bold text-black transition hover:scale-105">Register your team ↗</a></div><div className="mt-10 flex justify-between text-xs text-white/25"><span>HACKNOVATE &apos;26</span><span>BUILT WITH NEXT.JS · TAILWIND · GSAP</span></div></footer>
</main>}
